platform :ios, '12.0'
inhibit_all_warnings!

target 'MyDiary' do
  use_frameworks!

  pod 'RxSwift', '< 6.2.0'
  pod 'RxCocoa', '< 6.2.0'
  pod 'RxGesture', '< 4.1.0'
  pod 'RxDataSources', '<5.1.0'

  pod 'IQKeyboardManagerSwift', '< 6.6.0'
  pod 'SnapKit', '< 5.1.0'
  pod 'Then', '< 2.8.0'

end
